### ISSUE TITLE
Limited Program Memory for BabelFish in ATTiny85

### ISSUE THREAD

**Issue by ryanohoro** [kervinck/gigatron-rom#89] opened 2019-08-11 23:24 UTC
The current GT1 files loaded on the ATTiny85 (flash size < 10,000) includes TinyBASIC and leaves only 156 bytes of PROGMEM left for new feature development.

Since TinyBASIC is included in ROMv3, it should now only be loaded in larger devices (flash size >= 10,000).

This change would require Pluggy McPlugface users with < ROMv3 to remain on an earlier version of BabelFish for TinyBASIC.

**Comment by kervinck** [comment] 2019-08-12 19:35
Hi @ryanohoro, could you elaborate: is this a duplicate of #90 or does it serve another purpose? Removing TinyBASIC is the easiest method to free up space for new features. Back in the day I spent quite a bit of time to compress the TinyBASIC. object file and win something like 300 bytes. But in the end I decided it's not worth it to add all that complexity. (In a more reasonable development, files will be stored on a memory card connected to the SPI expander)

**Comment by ryanohoro** [comment] 2019-08-12 22:43
That sounds great!

This is not a duplicate. A pull request was opened with a code change to help resolve this issue, but I have closed it for now.

I understand you're also busy. If you'd like, I can finish any work you may think is appropriate to free up space, and do so in my own fork.

**Comment by kervinck** [comment] 2019-08-13 07:12
Another suggestion is is to do the LED work in Contrib/rynahoro/
It's then clearly visible for everyone interested, and we can always decide at which point to adapt it to the kit edition.
There is already code in BabelFish that sends commands _to_ the keyboard.

**Closed** 2019-08-24 07:25 UTC
Labels: enhancement
